apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-models-pvc
  namespace: argus
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-persistence
  resources:
    requests:
      storage: 50Gi
