apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argus-chroma-pvc
  namespace: argus-dev
  labels:
    app: argus
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
